package com.trialmanmode.music;

import net.runelite.api.VarPlayer;

/*
 * Music track unlock bitfields
 */
public enum MusicVarPlayers {
    MUSIC_TRACKS_UNLOCKED_1(20),
    MUSIC_TRACKS_UNLOCKED_2(21),
    MUSIC_TRACKS_UNLOCKED_3(22),
    MUSIC_TRACKS_UNLOCKED_4(23),
    MUSIC_TRACKS_UNLOCKED_5(24),
    MUSIC_TRACKS_UNLOCKED_6(25),
    MUSIC_TRACKS_UNLOCKED_7(298),
    MUSIC_TRACKS_UNLOCKED_8(311),
    MUSIC_TRACKS_UNLOCKED_9(346),
    MUSIC_TRACKS_UNLOCKED_10(414),
    MUSIC_TRACKS_UNLOCKED_11(464),
    MUSIC_TRACKS_UNLOCKED_12(598),
    MUSIC_TRACKS_UNLOCKED_13(662),
    MUSIC_TRACKS_UNLOCKED_14(721),
    MUSIC_TRACKS_UNLOCKED_15(906),
    MUSIC_TRACKS_UNLOCKED_16(1009),
    MUSIC_TRACKS_UNLOCKED_17(1338),
    MUSIC_TRACKS_UNLOCKED_18(1681),
    MUSIC_TRACKS_UNLOCKED_19(2065),
    MUSIC_TRACKS_UNLOCKED_20(2237),
    MUSIC_TRACKS_UNLOCKED_21(2950),
    MUSIC_TRACKS_UNLOCKED_22(3418),
    MUSIC_TRACKS_UNLOCKED_23(3575);
    private final int varPlayerId;

    MusicVarPlayers(int varPlayerId) {
        this.varPlayerId = varPlayerId;
    };

    public int getVarPlayerId() {
        return varPlayerId;
    }
}
